### ISSUE TITLE
Cut beacon beams and ropes

### ISSUE THREAD

**Issue by thomasrudin** [mt-mods/jumpdrive#32]
Edge cases for cutting off beams and ropes.
~~Maybe even disable jumping them~~

**Comment by int-ua** [comment]
Unfortunately disallowing green beacons may cause some issues with falling through floor on teleporting. I don't have an issue id for that yet, please add if you know it was already reported.

**Comment by thomasrudin** [comment]
> Unfortunately disallowing green beacons may cause some issues with falling through floor on teleporting. I don't have an issue id for that yet, please add if you know it was already reported.

I put that in another issue: #46
Just cutting them off will do the job, i've seen a lot of "lone" ropes out there :/

**Comment by OgelGames** [comment]
I think this can be closed, beacon beams cleanup themselves when a player returns to the area, and ropes should have been fixed in #51
