### ISSUE TITLE
Move chat messages away from jd API

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/jumpdrive#63]
Currently some digiline ops do and some dont. jump sends success and error messages also to chat.

Let caller decide and handle chatting and move it away from API

**Comment by thomasrudin** [comment]
Do you mean this message:

https://github.com/mt-mods/jumpdrive/blob/2847d07c2335d99eb4d87ff6ef2d1789945bf837/common.lua#L185

The other chat messages are all from within formspec callbacks...

**Comment by S-S-X** [comment]
> Do you mean this message:
> 
> https://github.com/mt-mods/jumpdrive/blob/2847d07c2335d99eb4d87ff6ef2d1789945bf837/common.lua#L185
> 
> The other chat messages are all from within formspec callbacks...
> 
> **EDIT**: another one here in the `jumpdrive.execute_jump()` function:
> 
> https://github.com/mt-mods/jumpdrive/blob/2847d07c2335d99eb4d87ff6ef2d1789945bf837/common.lua#L161

Yes, these two if there's no more. Seems tha player api stuff can also be removed with chat messages.

Formspec event handlers seems to be correct place for these as those have direct relation with user interaction.
