### ISSUE TITLE
fix ropes compat code

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/jumpdrive#69]
Seems to crash on the destroy part of the ropes with an unknown content_id:
https://github.com/pandorabox-io/pandorabox.io/issues/489

**Comment by tuedel** [comment]
This should be fixed now since https://github.com/minetest-mods/ropes/pull/20 has been merged.

**Comment by BuckarooBanzay** [comment]
thanks @tuedel, i also reverted the rope-disabling commit
