### ISSUE TITLE
Cleanup teleport tube compatibility hacks

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/jumpdrive#75]
Now that https://gitlab.com/VanessaE/pipeworks/-/merge_requests/24 is merged it should be possible to [leave pipeworks namespace alone](https://github.com/mt-mods/jumpdrive/blob/master/override/teleport_tube.lua#L67), cleanup significant amount of [hacky code duplicated from pipeworks](https://github.com/mt-mods/jumpdrive/blob/master/override/teleport_tube.lua#L3-L63) and use functions provided through [pipeworks.tptube table](https://gitlab.com/VanessaE/pipeworks/-/blob/477a02403421f87d957bd5acaf9d873f99930bae/teleport_tube.lua#L266-271).

- [x] Remove tp tube patch files https://github.com/mt-mods/jumpdrive/tree/master/patches
- [x] Cleanup or remove if possible https://github.com/mt-mods/jumpdrive/blob/master/override/teleport_tube.lua

**Comment by BuckarooBanzay** [comment]
Sounds good, i see when i have time for that and report back here before i start anything.
Just fyi: last time i switched to the overridden tp-tubes all of them had to be re-enabled with a formspec open/close, i want to try that first on the test-server before something like that happens again
