### ISSUE TITLE
Prevent vacuum from jumping

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/jumpdrive#76]
Replace vacuum with air on jumping.

## Use case

* Large scale pressurized landing structures don't get decompressed while jumping in

## Downsides

* Vacuum is unmovable again

**Comment by SwissalpS** [comment]
Upside far outweighs the downside. I need to check if we can still get vacuum into inventory, that was one way of willingly 'destroy' bases. (also bringing to earth and using in water as lights)

**Comment by OgelGames** [comment]
> I need to check if we can still get vacuum into inventory,

AFAIK, you can't, vacuum drops nothing: https://github.com/mt-mods/vacuum/blob/master/vacuum.lua#L17

If there was a way, then it would also make it possible to get bedrock, air, and other "illegal" nodes into inventory

**Comment by SwissalpS** [comment]
we managed to find ways to get vacuum and tried similar methods with bedrock and almost all placeable nodes.
So far we only got vacuum. It's a timing situation. Ask coil for more info.

**Comment by S-S-X** [comment]
Just for the record, I do have some air...

**Comment by SwissalpS** [comment]
I spent a couple minutes trying to get vacuum and failed. Good thing I still have stacks in storage :)
